### ISSUE TITLE
Pinch Zoom Issue

### ISSUE THREAD

**Issue by objectivecdeveloper** [mtabini/AFKPageFlipper#1]
Hi Marco, 
Thanks a lot for the great resource on PDF.
I have been working on the same. Also trying to add functionality in the code with the Pinch and Zoom.
In fact, I have added the UIGesturerecognizer for the ZOOM/PAN and MOVE. The zooming works fine but it turns out in blur quality of PDF, which makes pdf page unreadable.

It will be very greatful if you help to resolve this issue.

Thanks and Regards.

**Comment by objectivecdeveloper** [comment]
we have updated the source, which now enables user to pinch and zoom. You can find it in new commits. 

Thanks and Regards.

**Comment by mtabini** [comment]
Busy pushing a new app out, so it might be a while before I can look into this (also, the main point of AFKPageFlipper is the page flipping, the PDF is incidental to it, so I didn't spend that much time making it work). It looks like you need to refresh the contents of the PDF view whenever you change the zoom level so that it forces the PDF to draw at the given zoom level. This will make it look crisp again.

**Comment by objectivecdeveloper** [comment]
Hi, Managed to zoom the pdf, and surprisingly works great.
Thanks :)

**Comment by mtabini** [comment]
Ok, wonderful!
